### PR TITLE
1.3.0 / Swift 4

### PR DESCRIPTION
**Pull request by pcantrell**

### CODE REVIEW

**Comment by Reedyuk** [comment]
Nice work Paul, I'm sure you are aware of the issue with:
`Simultaneous accesses to 0x7f8abce14760, but modification requires exclusive access.
Previous access (a modification) started at Siesta NetworkRequest.broadcastResponse(_:) + 2338 (0x10717f042).
Current access (a read) started at:
0    libswiftCore.dylib                 0x000000010b101740 swift_beginAccess + 505
1    Siesta                             0x0000000107179f80 Net`

**Comment by pcantrell** [comment]
I thought I’d fixed it. Are you getting this on the current `swift-4` branch?

**Comment by Reedyuk** [comment]
Yes just checked now, it’s gone.

Thanks

Sent from my iPhone

On 3 Sep 2017, at 16:41, Paul Cantrell <notifications@github.com<mailto:notifications@github.com>> wrote:


I thought I’d fixed it. Are you getting this on the current swift-4 branch?

**Comment by pcantrell** [comment]
Awesome. Thanks for checking!

**Pull request merged**
