### PR TITLE
Update for Xcode 9.3/Swift 4.1

### PR DESCRIPTION
**Pull request by joaomvfsantos**
Basically I just did 2 things:
- Automatic Xcode upgrade of the project
- Replaced flatMap with compactMap where said map returned optionals

Note: Travis Build shall fail until it's updated to use Xcode 9.3 image

### CODE REVIEW

**Comment by edwardmp** [comment]
Was going to introduce a PR for the same.
But the tests are failing because `compactMap` is only implemented in Swift 4.1+.

Hence, the tests fail on Swift 4.0 and earlier. The solution should be to conditionally use compactMap/flatMap based on the Swift compiler version used.

**Comment by joaomvfsantos** [comment]
@edwardmp Hey! Yes that makes sense, I could do those changes. How would you suggest doing this? Using a pre processor macro like this:

```swift
#if swift(>=4.1)
// .compactMap
#else
// .flatMap
#endif
```

I confess I'm not used to use pre processor macros, as such my only concern is that I would probably duplicate a lot of code (at least the whole block inside the map function).

**Comment by edwardmp** [comment]
@pcantrell I would normally agree, but since flatMap is used in just 5 places it might make sense to do this the "easy" way. Although I do have to say that a lot of my dependencies cause warnings for the same issue, so I guess I'll be stuck with those warnings for a while!

**Comment by Linnk** [comment]
@joaomvfsantos Hi. In order to avoid code duplication as you said, you can store the closure in a variable. This way you only need one line inside the conditional cases.

For Example:

```swift
let stringNumbers = ["1", "2", "3", "x", "4", "5"]
let closure: (String) -> Int? = { Int($0) }

#if swift(>=4.1)
    let numbers = stringNumbers.compactMap(closure)
#else
    let numbers = stringNumbers.flatMap(closure)
#endif

print(numbers)
```

PS. I was about to make a PR about these annoying warnings lol, good think I checked first.

**Comment by edwardmp** [comment]
@Linnk 
Good idea! Can you submit a PR implementing this, at least, if @pcantrell  is willing to settle for this?

**Comment by Linnk** [comment]
@edwardmp Well, I was doing it… but then I read the comment about the siesta and swift versions and stuff. And I get it, I'm not fan either of those #if conditions.

**Comment by joaomvfsantos** [comment]
@Linnk Thanks for taking the time to give a concrete example. I started to doing an approach like that but after @pcantrell comment I did not proceed. His view also makes sense to me.

**Comment by pcantrell** [comment]
If we were going to simultaneously support Swift 4.0 and 4.1, I’d prefer to do it with a conditional extension, which can live in its own separate file and doesn’t clutter up usage sites:

```swift
#if !swift(>=4.1)
    extension Sequence
        {
        func compactMap<ElementOfResult>(_ transform: (Self.Element) throws -> ElementOfResult?) rethrows -> [ElementOfResult]
            { return try flatMap(transform) }
        }
#endif
```

However, as I said above, I don’t see any particular reason not to just require 4.1 in the next Siesta release. If somebody _does_ find a compelling reason to keep 4.0 support, we could add the above.

For now, if you want to get this PR passing CI, try updating the `.travis.yml` to require the newer Xcode.

**Comment by pcantrell** [comment]
Also P.S. I expect to be pulling together Siesta 1.4 in early May. There are some awesome new caching and custom request building features in the works, mostly complete; just have to survive the end of the semester first! If anybody wants a sneak preview, all that work is on the [`file-cache` branch](https://github.com/bustoutsolutions/siesta/compare/file-cache).

**Comment by joaomvfsantos** [comment]
@pcantrell I changed travis to use the Xcode 9.3 image but it's failing only on iPhone 4s simulator. Any ideas why?

**Pull request merged**
