### PR TITLE
codebeat badge

### PR DESCRIPTION
**Pull request by korzonek**
Guys, I see super results in codebeat. Good job! :) Would you please consider adding codebeat badge.

### CODE REVIEW

**Comment by pcantrell** [comment]
Hi Tomasz! Nice work on Codebeat! While I’m pleased to get an “A,” I have concerns about drawing attention to a machine-generated quality metric. I had a long email conversation with Marcin Wyszyński about this. Here’s what I wrote, edited a bit:

It’s nice to have problems flagged — and Codebeat chooses good ones to flag. I always like things that help me see code in a fresh way, and help me give attention to things I might have missed. However, when a linter / style checker / analysis tool is part of my normal dev flow, it keeps on nagging me with feedback long after that feedback has ceased to be useful.

For example, Codebeat flagged NetworkRequest.interpretResponse() and ResourceStatusOverlay.updateDisplay(). I think it was right to flag them. There’s complexity there that deserves attention. However, when I look at those two methods, IMHO they strike the right tradeoff. There are alternatives that would make those methods score better on Codebeat's complexity metric, but they’d be harder to read. Best as is. Flagged, reviewed, approved.

But there sits Codebeat’s grade, chastising me, perhaps even making managers or potential users nervous. And thus I suspend my own good judgement and bend the code to the tool. The tool ends up prioritizing the mindless over the mindful, the machine reader over the human reader — and thus makes me expend effort to make the code worse!

I’m happy to have issues flagged _once_ for consideration. I’m not happy to have them flagged _forever_ until I bend the code to the style checker’s will. This is a problem even when things are folded into a numeric quality metric — even if that metric currently scores high and makes the project look good! Metrics always draw attention to the things they know how to measure, and thus away from the things they don’t.

My wish is for a code analysis tool which flags **newly introduced issues for review**. Possible ways to do this:

- A Github hook that flags each PR with new quality issues it introduces.
- A hook that translates new issues into Github issues for the developers to review and consider.
- A Codebeat-managed review queue.

Any of those things would be quite helpful to me as a developer, and I’d happily integrate them into Siesta. They’re not pressuring me to suspend my good judgement, but still helping see things I might not have considered.

**Comment by korzonek** [comment]
We are currently working on nice integration of introduced quality issues with PR. Stay tuned :)

**Comment by pcantrell** [comment]
I will be eager to beta test it when it’s ready!

**Comment by pcantrell** [comment]
I'm closing this for now, but please do let me know when you have a “new quality flags introduced by pull request” feature ready to try.

**Comment by korzonek** [comment]
@pcantrell super! Thank you! We are almost there :) It was bigger task that we initially estimated :(

**Comment by pcantrell** [comment]
Isn't it always?

**Comment by korzonek** [comment]
@pcantrell You are right :) To be honest, the first version is already deployed to production, but there are coming improvements, and I would like you to fall in love with our support for pull requests :) ...or at least trust and like it :)

**Comment by korzonek** [comment]
@pcantrell support for pull request, together with new dashboard, support for Java, Kotlin, Obj-C, new dashboard, user management on projects level, enhanced slack notification and other improvements is available. Please give it a try. I hope you will like it :)

**Comment by pcantrell** [comment]
@korzonek I’m excited to try it! But I don’t see any of the pull request functionality. There’s no “pull requests” tab for Siesta on Codebeat, and nothing about it in the project settings.
screen shot 2016-08-16 at 10 02 17 am

**Comment by korzonek** [comment]
@pcantrell Pull Requests are available for only private repositories. I was not precise :( I'm sorry! We will support Pull Request for open source projects in the future but it requires changes in our architecture to support.

Here you can find a few screenshots https://codebeat.co/ios how it looks. Please sign up for private repo and please let us know what you think about it. We have 14-day free trial so your credit card won't be charged.

I'm sorry, I should be more precise Pull Request support is not available for open source projects.

**Comment by pcantrell** [comment]
Well, it’s Siesta I’d be interested in using Codebeat for, so please do let me know if and when it’s available for open source projects!

**Comment by korzonek** [comment]
👍

**Pull request closed without merging**
