### PR TITLE
Add support for tvOS

### PR DESCRIPTION
**Pull request by omidontop**
Adding support for tvOS...

Related: https://github.com/bustoutsolutions/siesta/issues/28

### CODE REVIEW

**Comment by pcantrell** [comment]
Great, thanks! Are you using Siesta in a tvOS app? Is it working for you? Do the specs run?

I don't want to officially declare tvOS support until there’s confirmation from real projects that it’s working properly.

**Comment by omidontop** [comment]
@pcantrell Cheers! I just started working on this project and got it to compile today with the updated specs. So far so good and it compiles nicely. I thought I'd create the PR early to keep you updated as I go forward.

**Comment by pcantrell** [comment]
Excellent, please do. I’d love to officially add tvOS support once it’s confirmed to work.

**Comment by omidontop** [comment]
Absolutely, I need that too.

**Comment by snoozemoose** [comment]
@pcantrell I've been using Siesta in a tvOS app for nearly 2 years now using a similar patch (requiring tvOS 10.0 instead) and it has been working very good.

**Comment by pcantrell** [comment]
Thanks, @snoozemoose, that’s great to know!

**Comment by omidontop** [comment]
@pcantrell I can now safely say that Siesta works very well on tvOS and the changes in this PR was the only thing needed for that matter.

**Comment by omidontop** [comment]
@pcantrell It would be great if we can merge this in. If there's anything else associated with this merge request that needs to be done, I will try to help.

**Comment by pcantrell** [comment]
Yes! Sorry to leave you hanging. I’m working on this now.

I’m doing a pass now to change all the settings for the tvOS targets to match the other targets as closely as possible. There are currently several places where there are minor internal differences that don’t stop the tvOS targets from working, but might cause trouble in the future (e.g. differences in how build settings specify relative paths). I’m also enabling the SiestaUI target for tvOS, where it should work other than lacking a default .xib file for the status overlay.

**Comment by pcantrell** [comment]
I’ve pushed the build setting changes. While I get Travis sorted out, @omidontop, would you please try my latest push to this branch on your project and make sure my setting changes work on your end?

**Comment by omidontop** [comment]
@pcantrell Great work! Thank you so much for picking this up again. Of course I can test it :) Give me a sec.

**Comment by omidontop** [comment]
@pcantrell It compiles and works just fine!

**Comment by pcantrell** [comment]
Fantastic! Now I just have to get tvOS working on CI, then I’ll merge.

**Comment by omidontop** [comment]
Is the scheme name correct? You know with the whitespaces and all...

```-scheme Siesta tvOS ```

**Comment by pcantrell** [comment]
It’s some more fiddly mistake having to do with mismatches between the various names different Xcode CLI tools use for simulator platforms & versions. Trying different settings in between making dinner here.

Fair warning: once I have it figured out, I’m going to roll up all the intermediate “fiddling with Travis” commits and force push so we don’t end up with a dozen Travis experiments littering the history.

**Comment by pcantrell** [comment]
OK, it’s working! Couldn’t get CI to work with any version of tvOS except 12.1, but I’m pretty sure it’s a Travis / Xcode issue and not a Siesta issue, so … oh well. Merging!

**Comment by omidontop** [comment]
@pcantrell Bravoo! Thanks a lot for the awesome work! 🍺 Had many more bits and pieces involved than I imagined! Do you also have any new releases scheduled?

**Comment by pcantrell** [comment]
Not scheduled, but planning to cut one whenever I finally get the new FileCache stuff sorted out.

**Comment by pcantrell** [comment]
And thanks to you and everyone who tried it out on tvOS! It was crucial having real users for this.

**Pull request merged**
