### PR TITLE
Structured pipeline

### LINKED ISSUE #32: Allow EntityCache to function at any point in the transformer pipeline
EntityCache currently must store and return only the values at the very end of the transformer pipeline.

This works well when the end result of the pipeline is an easily serializable type such as text or JSON:

siesta pipeline 1

However, it’s problematic when the transform pipeline produces a model, which can be difficult for an `EntityCache` to store and retrieve:

siesta pipeline 2

Attempts to solve this problem by keeping models in a database quickly become problematic:

- The database needs to be able to look up models by REST URL, which mixes abstraction layers and leads to hackish workarounds.
- The `EntityCache` API is not designed to work with databases. (For example, it wants to pass cached entities across threads, which Realm doesn’t like.)

Suppose, however, that an `EntityCache` could insert itself at _any_ point in the transformer pipeline and not just the _end_. In other words, this is currently the only supported structure:

    → JSON transformer → Model transformer → (EntityCache) →

…but suppose the pipeline instead supported this:

    → JSON transformer → (EntityCache) → Model transformer →

When there is a cache hit, the pipeline would pick up immediately after the cache's position in the pipeline. An `EntityCache` could then work only with its preferred data type:

siesta pipeline 3

…or even:

siesta pipeline 4

This would require some hard thought in the plumbing, but seems to make sense. @annicaburns, would this solve the problems you were having with `EntityCache`? Would you still want to use Realm even with a mechanism like this in place?

### LINKED ISSUE #47: Better URL Pattern Matching
I have setup a handful of routes such as: 

```
 api.configureTransformer("/products/filters") { returns Filter }
 api.configureTransformer("/products/*") { returns Product }
 api.configureTransformer("/products/*/market") { returns Market }
```

When the '/products/filters' resource is loaded it handles it then passes 'Filter' objects into the 'products/*' handler which expects a JSON (SwiftyJSON) object. So of course the 'WrongTypeInTranformerPipeline' error pops up.

It would be nice to either allow a ResponseTransformer to say "no more transforming, we are done" or allow for better pattern matching in the URLs such as specifying the wildcard item should be an INT.

### PR DESCRIPTION
**Pull request by pcantrell**
This PR resolves #32. It contains two significant changes:

- There is a new `Pipeline` API for configuring caches and transformers.
- `EntityCache` now uses opaque keys instead of strings, which leaves room for important future features.

These changes are open for discussion. Please post feedback.

## Concept

Transformers now live in a pipeline with named stages:

siesta pipeline

Clients can customize the set of stages and their order.

Each stage has zero or more transformers:

siesta pipeline 2

…and a cache:

siesta pipeline 3

During response processing, each cache receives an entity for writing _after_ all the stage’s transformers have run.

When reinflating a new resource, Siesta checks each cache in turn starting with the _end_ of the pipeline. If there is a cache hit, Siesta takes whatever the cache returned and runs it through the pipeline’s subsequent stages.

## API

The opaque `resourceTransformers` config property is gone.  Instead, configure transformers by attaching them to a pipeline stage:

```swift
service.configure {
    $0.config.pipeline[.parsing].add(SwiftyJSONTransformer, contentTypes: ["*/json"])
    $0.config.pipeline[.cleanup].add(GithubErrorMessageExtractor())
}
```

Each stage has an optional cache:

```swift
service.configure {
    $0.config.pipeline[.rawData].cache = encryptedFileCache
    $0.config.pipeline[.model].cache = realmCache
}
```

### Replacing / Overriding Transformers

The ability to identify transformers by stage creates the new ability to remove or replace specific transformers in the pipeline, a frequently requested feature. To this end, `Service.configureTransformer(…)` will no longer always append the transformer; instead, it will by default _replace_ the transformer at the `model` stage:

```swift
service.configureTransformer("/users/*") {
  User(json: $0.content)
}

// ...is shorthand for:

service.configureTransformer("/users/*", atStage: .model, replaceExisting: true) {
  User(json: $0.content)
}

// ...which is shorthand for:

service.configure("/users/*") {
    $0.config.pipeline[.model].removeTransformers()
    $0.config.pipeline[.model].add(
        ResponseContentTransformer(
            User(json: $0.content)))
}
```

This provides a nice mechanism for overriding wildcards with specific model mappings, which fixes #47:

```swift
service.configureTransformer("/products/*") { Product(...) }
service.configureTransformer("/products/filters") { Filter(...) }  // overrides line above
```

### Stages

The default stages are:

- `rawData`: unprocessed data (to attach cache; wouldn’t typically have transformers at this stage)
- `decoding`: bytes → bytes: decryption, decompression, etc.
- `parsing`: bytes → ADT / general type: JSON, UIImage, etc.
- `model`: general object → model
- `cleanup`: catch-all for stuff at the end (Maybe “postprocessing” instead?)

Client projects can customize this on a per-service or per-resource basis:

```swift
extension PipelineStageKey {
    static let
        munging   = PipelineStageKey(description: "munging"),
        twiddling = PipelineStageKey(description: "twiddling")
}
```
```swift
service.configure {
    $0.config.pipeline.order = [.rawData, .munging, .twiddling, .cleanup]
}
```

### CODE REVIEW

**Comment by alecgorge** [comment]
@pcantrell been following this project since December waiting for this to land and I'm very excited about it! Thank you so much for your hard work and excellent documentation of what you are doing. These changes make the app I have in mind for a side project much more accomplishable in the limited time I have.

**Comment by alecgorge** [comment]
Also, @pcantrell how do you make those cool flow charts? Do you do them by hand or do you have a tool that can generate them?

**Comment by pcantrell** [comment]
Thanks, @alecgorge! If you have a chance to try these API changes this week, please let me know if things do or don’t work well for you. I’d love to gather feedback on these changes before putting them in an official release.

I made the diagrams in OmniGraffle. It’s great for all things boxes & arrows.

**Comment by alecgorge** [comment]
@pcantrell I'm not sure I'll have a chance this week (still in the design phase myself and honestly I'm changing a few things based on the possibilities here) but I'll definitely get to playing around with it soon and I'll write up some feedback or a PR if necessary. Thanks again!

**Comment by VDKA** [comment]
@pcantrell, the Pipeline changes coupled with the request method specific transformers are great. Using them currently.

**Pull request merged**
