### PR TITLE
Re-support iOS 8

### PR DESCRIPTION
**Pull request by pcantrell**
Restores support for iOS 8.

Alamofire dropped iOS 8 support, and I’ve had trouble figuring out how to make the specs run themselves against Alamofire when it is available _and_ still compile under iOS 8. For now, we’ll just have to live without iOS 8 properly tested.

(Any help on this is welcome!)

### CODE REVIEW

**Comment by pcantrell** [comment]
@jordanpwood Wanting to get an official Swift 3 release out the door, so I put this together. It resolves #111. No Travis on iOS 8 for now, but when I manually comment out the AF stuff, the specs do pass on 8. So you should be GTG.

**Comment by jordanpwood** [comment]
Thanks @pcantrell!  I was working on getting my own code migrated to Swift 3 on Friday, so I hadn't gotten to this yet.  Someday I'll have to buy you a 🍺.

**Comment by pcantrell** [comment]
You bet. ☕️ is my vice if you’re looking to raise a glass to Siesta. Your work is not done, though: this release needs lots of sanity checking after the big Swift 3 migration! So LMK how it goes.

**Comment by jordanpwood** [comment]
It looks like `s.ios.deployment_target` is still set to 9.0 in `Siesta.podspec` in the Swift 3 release, @pcantrell.

**Comment by pcantrell** [comment]
Ah, indeed. Good catch! Fixed now on master.

**Pull request merged**
