### PR TITLE
Xcode8 + Swift 2.3 Migration

### PR DESCRIPTION
**Pull request by andrewloyola**
Merging in the handful of Xcode 8 Migration tool results, it should now build on XCode8b3 

Included Changes
- Misc api updates (NSURL primarily)
- Turning on Whole Module Optimization (suggested by XCode)

### CODE REVIEW

**Comment by pcantrell** [comment]
Hi Andrew! I can’t merge these changes yet, because `absoluteString` becoming optional in 2.3 is a breaking change, and the lib thus won’t work under 2.2 when we make that leap.

As per the [plans for 2→3 migration](http://bustoutsolutions.github.io/siesta/guide/faq/#roadmap-1-0), I’m going to cut a 3.0 (and maybe 2.3) branch only after finalizing API changes in 2.2. I’ll hold this PR open for reference until then.

**Comment by andrewloyola** [comment]
makes sense.  thanks for the update!

**Comment by pcantrell** [comment]
@andrewloyola I think the moment has come. Care to rebase / redo the Swift 2.3 migration off the current master? If you send the PR, I’ll cut a `swift2.3` branch from it.

**Comment by andrewloyola** [comment]
sure! i will take a look at that shortly

**Comment by andrewloyola** [comment]
@pcantrell done.

**Comment by pcantrell** [comment]
@andrewloyola Thanks!

**Pull request merged**
